# Generated by Django 3.2.4 on 2021-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210611_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='approved_comment',
            new_name='approved_report',
        ),
    ]
