# Generated by Django 3.0.7 on 2021-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.CharField(default='', max_length=100),
        ),
    ]
