# Generated by Django 3.0.7 on 2021-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='singer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
