# Generated by Django 3.0.7 on 2021-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='singer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
